# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://row.gymshark.com/pages/shop-men")
    self.driver.set_window_size(1552, 832)
    element = self.driver.find_element(By.CSS_SELECTOR, ".header_action-bar-item-wrap__m_Rhz .icon-user")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".header_action-bar-item-wrap__m_Rhz .icon-user").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("john@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Test!@3")
    self.driver.find_element(By.CSS_SELECTOR, ".ulp-button-icon").click()
    self.driver.find_element(By.NAME, "action").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_widget").click()
  
