# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRecordingandReplaying():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_recordingandReplaying(self):
    self.driver.get("https://row.gymshark.com/pages/shop-men")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".header_mobile-header-search__AfHPq > .search_search-trigger__U6dOW").click()
    self.driver.find_element(By.ID, "gymshark-header-search-search-enter").send_keys("tshirt")
    self.driver.find_element(By.ID, "gymshark-header-search-search-enter").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, ".header_mobile-header-search__AfHPq > .search_search-trigger__U6dOW")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".product-card_product-card__CIqIf:nth-child(2) .image_image-wrap-second__5psYi")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".product-card_product-card__CIqIf:nth-child(1) .image_image-wrap-second__5psYi")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".image_image-wrap-second--active__DotsT").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".image-gallery_gallery--item__OW3UF:nth-child(2) > img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart_section__GygMh:nth-child(5) .size_size__saJiQ:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart_button-container__aKAUo:nth-child(6) .button_success-overlay__aqLb7").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "div > .product-card_product-card__CIqIf:nth-child(1) .product-card_product-title-link__jDI6f")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "minicart-discount-code").click()
    self.driver.find_element(By.ID, "minicart-discount-code").send_keys("Promo")
    self.driver.find_element(By.CSS_SELECTOR, ".button_button--position-left__pspoh:nth-child(1) > .button_loading-overlay__uvQ6f").click()
    self.driver.execute_script("window.scrollTo(0,333.3333435058594)")
    self.driver.close()
  
